export const questions = [
  { id: 1, question: "What does HTML stand for?", answer: "HyperText Markup Language" },
  { id: 2, question: "What does CSS stand for?", answer: "Cascading Style Sheets" },
  { id: 3, question: "This is your code editor, type 'Welcome to Code4Change'", answer: "Welcome to Code4Change" },
  { id: 4, question: "Turn 'Welcome to Code4Change' into an h1 element.", answer: "<h1>Welcome to Code4Change</h1>" },
  { id: 5, question: "Turn 'Full Stack Curriculum' text into an h2 element.", answer: "<h2>Full Stack Curriculum</h2>" },
  { id: 6, question: "Turn 'Learn the skills to become a full stack developer' into a paragraph element.", answer: "<p>Learn the skills to become a full stack developer</p>" },
  { id: 7, question: "What does RAM stand for?", answer: "Random Access Memory" },
  { id: 8, question: "Add <!DOCTYPE html> and html element with lang='en'.", answer: "<!DOCTYPE html>\n<html lang=\"en\">" },
  { id: 9, question: "Add a head element with a title 'Cafe Menu'.", answer: "<head><title>Cafe Menu</title></head>" },
  { id: 10, question: "Write a Python function called greet that prints 'Hello'.", answer: "def greet():\n    print('Hello')" },
  { id: 11, question: "What is the difference between let and var in JavaScript?", answer: "let is block-scoped, var is function-scoped" },
  { id: 12, question: "How do you connect to a database using SQL?", answer: "Use a connection string or client to connect" },
  { id: 13, question: "Write a basic SELECT query to get all rows from table Users.", answer: "SELECT * FROM Users;" },
  { id: 14, question: "What does 'DBMS' stand for?", answer: "Database Management System" },
  { id: 15, question: "How do you add a comment in HTML?", answer: "<!-- comment -->" },
  { id: 16, question: "How do you add a comment in CSS?", answer: "/* comment */" },
  { id: 17, question: "How do you add a comment in JavaScript?", answer: "// comment" },
  { id: 18, question: "Write a JavaScript arrow function called sum that returns a + b.", answer: "const sum = (a, b) => a + b;" },
  { id: 19, question: "What is the difference between const, let, and var?", answer: "const cannot be reassigned, let is block-scoped, var is function-scoped" },
  { id: 20, question: "How do you center an element using CSS flexbox?", answer: "display: flex; justify-content: center; align-items: center;" },
  { id: 21, question: "What is the difference between GET and POST requests?", answer: "GET retrieves data, POST sends data" },
  { id: 22, question: "Write a SQL query to create a table called Products.", answer: "CREATE TABLE Products (id INT, name TEXT);" },
  { id: 23, question: "Write a Python loop that prints numbers 1 to 5.", answer: "for i in range(1,6):\n    print(i)" },
  { id: 24, question: "What does API stand for?", answer: "Application Programming Interface" },
  { id: 25, question: "What is JSON used for?", answer: "To store and transport data" },
  { id: 26, question: "Write CSS to make text bold.", answer: "font-weight: bold;" },
  { id: 27, question: "Write CSS to change background color to red.", answer: "background-color: red;" },
  { id: 28, question: "How do you declare an array in JavaScript?", answer: "const arr = [];" },
  { id: 29, question: "Write a Python list with numbers 1,2,3.", answer: "my_list = [1,2,3]" },
  { id: 30, question: "What does SQL SELECT do?", answer: "Retrieves data from a table" },
  { id: 31, question: "Write a Python function that returns x squared.", answer: "def square(x):\n    return x*x" },
  { id: 32, question: "What is the difference between inline and block elements in HTML?", answer: "Inline elements don't break line, block elements do" },
  { id: 33, question: "How do you link a CSS file in HTML?", answer: "<link rel=\"stylesheet\" href=\"style.css\">" },
  { id: 34, question: "Write HTML for an image with src 'logo.png'.", answer: "<img src=\"logo.png\" />" },
  { id: 35, question: "Write a Python dictionary with key 'name' and value 'Euel'.", answer: "my_dict = {'name':'Euel'}" },
  { id: 36, question: "Write a SQL query to delete all rows from Users.", answer: "DELETE FROM Users;" },
];
